#include <iostream>
#include <vector>

using namespace std;

/*
 * Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 *
 */

char findTheDifference(string s, string t) {
    vector<int> cnt(26, 0);
    for(int i = 0; i < t.length(); i++)
        cnt[t[i] - 'a'] += 1;
    for(int i = 0; i < t.length(); i++)
        cnt[s[i] - 'a'] -= 1;
    for(int i = 0; i < 26; i++) {
        if(cnt[i] != 0)
            return i + 'a';
    }
    return ' ';
}
